sudo: false
language: cpp

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-multilib
      - g++-4.9-multilib
  artifacts:
    debug: true

before_install:
  - git submodule update --init --recursive
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install 4.2.6
  - nvm use 4.2.6
  - npm install -g gulp bower node-pre-gyp nw-gyp

install:
  - bower i
  - npm i

script:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then npm run client-build-linux64; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then npm run client-build-osx; fi
